import { initializeApp } from 'firebase/app';
import { getFirestore, doc, getDoc, setDoc, onSnapshot } from 'firebase/firestore';
import { 
  getAuth, 
  signInWithEmailAndPassword, 
  createUserWithEmailAndPassword 
} from 'firebase/auth';
import { FlatManagerData } from '../types';

// Load configurations directly from the config generated by the setup
import firebaseConfig from '../../firebase-applet-config.json';

const app = initializeApp(firebaseConfig);

// Initialize Firestore database instance
export const db = (firebaseConfig as any).firestoreDatabaseId && (firebaseConfig as any).firestoreDatabaseId !== '(default)'
  ? getFirestore(app, (firebaseConfig as any).firestoreDatabaseId)
  : getFirestore(app);

// Initialize Firebase Auth
export const auth = getAuth(app);

// Initialize secondary auth instance to create users without logging out the primary session
const secondaryApp = initializeApp(firebaseConfig, 'secondaryAuthApp');
const secondaryAuth = getAuth(secondaryApp);

const DOCUMENT_PATH = ['flatData', 'myflat'] as const;

/**
 * Recursively cleans data to ensure Firestore never receives `undefined` fields.
 */
function sanitizeForFirestore<T>(val: T): T {
  if (val === undefined) {
    return null as unknown as T;
  }
  if (val === null) {
    return null as unknown as T;
  }
  if (Array.isArray(val)) {
    return val.map(item => sanitizeForFirestore(item)) as unknown as T;
  }
  if (typeof val === 'object') {
    const cleaned: Record<string, any> = {};
    for (const [key, value] of Object.entries(val)) {
      if (value !== undefined) {
        cleaned[key] = sanitizeForFirestore(value);
      }
    }
    return cleaned as T;
  }
  return val;
}

export async function fetchCloudData(): Promise<FlatManagerData | null | undefined> {
  try {
    const docRef = doc(db, ...DOCUMENT_PATH);
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return snap.data() as FlatManagerData;
    }
    // Document does not exist in Firestore
    return undefined;
  } catch (error: any) {
    // Gracefully handle "client is offline" or network latency
    if (error.code === 'unavailable' || (error.message && error.message.includes('offline'))) {
      console.debug('Firestore currently offline or unavailable');
    } else {
      console.warn('Firebase Firestore fetch notice:', error?.message || error);
    }
    return null;
  }
}

export async function saveCloudData(data: FlatManagerData): Promise<void> {
  try {
    const docRef = doc(db, ...DOCUMENT_PATH);
    const sanitized = sanitizeForFirestore({
      ...data,
      updatedAt: new Date().toISOString()
    });
    await setDoc(docRef, sanitized);
    
    // Background sync users to Firebase Authentication
    syncAllUsersToAuth(data).catch(err => {
      console.debug('Background Auth sync note:', err);
    });
  } catch (error: any) {
    console.warn('Firebase Firestore save notice:', error?.message || error);
  }
}

export function subscribeToCloudData(onUpdate: (data: FlatManagerData) => void): () => void {
  const docRef = doc(db, ...DOCUMENT_PATH);
  return onSnapshot(docRef, (snapshot) => {
    if (snapshot.exists()) {
      onUpdate(snapshot.data() as FlatManagerData);
    }
  }, (error) => {
    console.warn('Firestore subscription notice:', error?.message || error);
  });
}

// Sync a single user to Firebase Authentication
export async function syncUserToFirebaseAuth(loginId: string, passwordStr: string): Promise<void> {
  if (!loginId || !passwordStr || passwordStr.length < 6) return;
  const email = `${loginId.toLowerCase().trim()}@myflat.com`;
  
  try {
    await createUserWithEmailAndPassword(secondaryAuth, email, passwordStr);
    console.log(`Successfully synced user to Firebase Authentication: ${email}`);
  } catch (error: any) {
    if (error.code === 'auth/email-already-in-use') {
      // User is already registered in Firebase Authentication
      // This is expected and normal
    } else {
      console.warn(`Auth sync note for ${email}:`, error.message);
    }
  }
}

// Sync all users to Firebase Auth
export async function syncAllUsersToAuth(data: FlatManagerData): Promise<void> {
  try {
    // 1. Sync Owner Account
    await syncUserToFirebaseAuth('owner', 'owner123');

    // 2. Sync all room/tenant accounts
    for (const room of data.rooms) {
      if (room.loginId && room.loginPassword) {
        await syncUserToFirebaseAuth(room.loginId, room.loginPassword);
      }
    }
  } catch (err: any) {
    console.warn('Batch sync note for Firebase Auth:', err?.message || err);
  }
}

// Real-time Authentication and Verification at Login
export async function loginWithFirebaseAuth(loginId: string, passwordStr: string): Promise<boolean> {
  const email = `${loginId.toLowerCase().trim()}@myflat.com`;
  
  // 1. First attempt to sign in with Firebase Auth directly
  try {
    await signInWithEmailAndPassword(auth, email, passwordStr);
    console.log(`Logged in successfully via Firebase Auth: ${email}`);
    return true;
  } catch (error: any) {
    // If sign in failed because user might not exist yet, attempt registration
    if (
      error.code === 'auth/user-not-found' || 
      error.code === 'auth/invalid-credential' || 
      error.code === 'auth/invalid-login-credentials'
    ) {
      try {
        await createUserWithEmailAndPassword(secondaryAuth, email, passwordStr);
        console.log(`Created missing Firebase Auth user account during login sync: ${email}`);
        
        // Try logging in again now that the account is created
        await signInWithEmailAndPassword(auth, email, passwordStr);
        return true;
      } catch (createErr: any) {
        if (createErr.code === 'auth/email-already-in-use') {
          // Account already exists in Firebase Auth; the login failure is simply due to wrong password
          console.debug(`Firebase Auth account already exists for: ${email}`);
        } else {
          console.warn(`Firebase Auth registration sync note:`, createErr.message || createErr);
        }
      }
    } else {
      console.debug(`Firebase Auth login attempt result: ${error.code || error.message}`);
    }
  }
  return false;
}
